name: CI

on:
  push:
    branches:
      - /*
  pull_request:
    branches:
      - main
  schedule:
  - cron: "0 5 * * 1-5"
  
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test coverage-badge-py
    steps:
      - name: Checkout
        uses: actions/checkout@v3
